name: Keep Heroku Alive

on:
  # push:
  #   branches: [master]
  schedule:
    - cron: '*/20 * * * *'

jobs:
  github-actions:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    name: Node.js ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Keep Heroku Alive
        run: curl -v https://tokenize-socket.herokuapp.com/
